### ISSUE TITLE
How can I close the logrus goroutine?

### ISSUE THREAD

**Issue by CaledoniaProject** [sirupsen/logrus#1348]
I have multiple goroutines that would create a new log file with logrus. When I stop those goroutines, the logrus goroutine remain open. e.g I have 10+ logrus goroutine running

```
goroutine 22496 [chan receive]:
gopkg.in/natefinch/lumberjack%2ev2.(*Logger).millRun(0xc003f2c960)
	/root/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.0.0/lumberjack.go:379 +0x45
created by gopkg.in/natefinch/lumberjack%2ev2.(*Logger).mill.func1
	/root/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.0.0/lumberjack.go:390 +0x96
```

How can I close them? I've tried the following and it does not seem to work:

```
mylogger.Infof("task %v finished", scan.task.Id)

if file, ok := mylogger.Out.(*os.File); ok {
	file.Sync()
	file.Close()
} else if handler, ok :=mylogger.Out.(io.Closer); ok {
	handler.Close()
}
```

What do you suggest?

**Comment by CaledoniaProject** [comment]
The problem is from lumberjack, not related to logrus
