### ISSUE TITLE
Concurrent map errors

### ISSUE THREAD

**Issue by tejasmanohar** [sirupsen/logrus#364]
I've been running into this error while using logrus, especially with larger log payloads. Not sure if this has the same root cause of #295 or not.

```
fatal error: concurrent map read and map writeINFO[0035]
​
goroutine 44 [running]:
runtime.throw(0x92f2a0, 0x21)
  /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:547 +0x90 fp=0xc82066f7e0 sp=0xc82066f7c8
runtime.mapaccess1_faststr(0x6e6de0, 0xc820149350, 0x888940, 0xa, 0xc82066f980)
  /usr/local/Cellar/go/1.6.2/libexec/src/runtime/hashmap_fast.go:202 +0x5b fp=0xc82066f840 sp=0xc82066f7e0
github.com/Sirupsen/logrus.(*TextFormatter).printColored(0xc82011cac0, 0xc8204abc70, 0xc82041bcc0, 0xc820896c80, 0x5, 0x5, 0x910460, 0x19)
  .../Godeps/_workspace/src/github.com/Sirupsen/logrus/text_formatter.go:120 +0x439 fp=0xc82066fa38 sp=0xc82066f840
github.com/Sirupsen/logrus.(*TextFormatter).Format(0xc82011cac0, 0xc82041bcc0, 0x0, 0x0, 0x0, 0x0, 0x0)
  .../Godeps/_workspace/src/github.com/Sirupsen/logrus/text_formatter.go:81 +0x566 fp=0xc82066fbd8 sp=0xc82066fa38
github.com/Sirupsen/logrus.(*Entry).Reader(0xc82041bcc0, 0xc81c54f402, 0x0, 0x0)
  .../Godeps/_workspace/src/github.com/Sirupsen/logrus/entry.go:44 +0x67 fp=0xc82066fc70 sp=0xc82066fbd8
github.com/Sirupsen/logrus.Entry.log(0xc820131400, 0xc820149350, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x22102, 0xc8208c2ea0, ...)
  .../Godeps/_workspace/src/github.com/Sirupsen/logrus/entry.go:94 +0x296 fp=0xc82066fd98 sp=0xc82066fc70
github.com/Sirupsen/logrus.(*Entry).Error(0xc820119440, 0xc82066fea0, 0x1, 0x1)
  .../Godeps/_workspace/src/github.com/Sirupsen/logrus/entry.go:145 +0x8c fp=0xc82066fe08 sp=0xc82066fd98
main.(*Source).Run.func1(0xf50470, 0xc820120178, 0xc820119440, 0xc82011d740)
```

**Comment by Sirupsen** [comment]
Can you provide a reproducible test-case?

**Comment by tejasmanohar** [comment]
We found the root cause to be when you set a hook that mutates the log payload. Do you have another suggestion on how to do this?

```
package log

import "github.com/Sirupsen/logrus"

type infoHook struct {
	Program string
	Version string
}

func (s *infoHook) Levels() []logrus.Level {
	return []logrus.Level{
		logrus.PanicLevel,
		logrus.FatalLevel,
		logrus.ErrorLevel,
		logrus.WarnLevel,
		logrus.InfoLevel,
		logrus.DebugLevel,
	}
}

func (s *infoHook) Fire(entry *logrus.Entry) error {
	entry.Data["program"] = s.Program
	entry.Data["version"] = s.Version
	return nil
}
```

**Comment by iancmcc** [comment]
I'm seeing this as well, and I have a similar hook, although I'm not seeing that hook's Fire() being called in any other goroutine in the panic output. Maybe it already executed. @tejasmanohar, how did you narrow it down? I'll see if I can produce a set of repro steps.

**Comment by tejasmanohar** [comment]
@iancmcc Only from the stack trace

**Comment by iancmcc** [comment]
Nope, all my efforts to create a test case that reproduces it have failed. I'll keep trying, though.

**Comment by tejasmanohar** [comment]
Same here

**Comment by iancmcc** [comment]
Here's a repro!

https://gist.github.com/iancmcc/385fb2d1ec628cf11840d6f0f601b300

Seems to repro every time with this, although if it's not happening try running it with race detection. Same problem, concurrent access to entry.Data. I've hacked around it temporarily by sticking a mutex on entry to deal with it, but I doubt that'll be preferred as a real fix for performance reasons.

**Comment by dgsb** [comment]
Could not reproduce anymore, seems fixed.
